# Generated by Django 4.1.7 on 2023-03-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="name",
            field=models.CharField(default="a", max_length=20),
            preserve_default=False,
        ),
    ]
